name: todo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  sign_in_with_apple: ^6.1.4
  win32: ^5.11.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
